config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :events
  root 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
validates :summary, :description, :location, :attendees, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]

    def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
        data = access_token.info
        #if (User.admins.include?(data.email))
            user = User.find_by(email: data.email)
            if user
                user.provider = access_token.provider
                user.uid = access_token.uid
                user.token = access_token.credentials.token
                user.save
                user
            else
                user = User.new(
                #name: access_token.extra.raw_info.name,
                email: data.email ? data.email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
                password: Devise.friendly_token[0,20],
                provider: access_token.provider,
                uid: access_token.uid,
                token: access_token.credentials.token
                )
                #user.skip_confirmation!
                user.save!
                user
                #redirect_to new_user_registration_path, notice: "Error."
            end
        #end
    end

    def self.exchange_refresh_token( refresh_token )
      client = Google::APIClient.new
      client.authorization.client_id = ENV['CONSUMER_KEY']
      client.authorization.client_secret = ENV['CONSUMER_SECRET']
      client.authorization.grant_type = 'refresh_token'
      client.authorization.refresh_token = refresh_token

      client.authorization.fetch_access_token!
      client.authorization
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :index]

    def index
        @events = Event.all
        # This statement will provide a list of calendar events for the user.
        if user_signed_in?
            client = Google::APIClient.new
            client.authorization.access_token = current_user.token
            service = client.discovered_api('calendar', 'v3')

            @list_events = client.execute(
                :api_method => service.events.list,
                :parameters => {'calendarId' => current_user.email},
            ).data
        end
    end

    def show
        @event = Event.find(params[:id])
    end

    def new
        @event = Event.new
    end

    def create
        @event = Event.new(event_params)

        if @event.save
            send_json
            redirect_to events_path
        else
            redirect_to root_path
            flash[:error] = "There was an error creating your event."
        end
    end

    private
    def send_json
        g_event = {
            'summary' => @event.summary,
            'description' => @event.description,
            'location' => @event.location,
            'start' => { 'dateTime' => @event.start.to_datetime.rfc3339 },
            'end' => { 'dateTime' => @event.end.to_datetime.rfc3339 },
            'attendees' => [{ 'email' => current_user.email }]
            #@event.attendees.to_s.split(',').collect(&:strip)
        }

        client = Google::APIClient.new
        client.authorization.access_token = current_user.token
        service = client.discovered_api('calendar', 'v3')

        client.execute(
            :api_method => service.events.insert,
            :parameters => {'calendarId' => current_user.email },
            :body => JSON.dump(g_event),
            :headers => {'Content-Type' => 'application/json'})

    end

    def event_params
        params.require(:event).permit(:summary, :description, :location, :start, :end, :attendees).merge(:owner => current_user.id)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
        @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

        if @user
            flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
            sign_in_and_redirect @user, :event => :authentication
        else
            redirect_to new_user_session_path, notice: 'Access Denied'
        end
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<% if user_signed_in? %>
    <iframe src="https://www.google.com/calendar/embed?title=<%= current_user.email %>&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=<%= current_user.email %>&amp;color=%232952A3&amp;ctz=America%2FNew_York" style=" border-width:0 " width="800" height="600" frameborder="0" scrolling="no"></iframe><br>
    <%= link_to "New Event", new_event_path, class: 'button' %><br>
    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'button' %>
<% else %>
    <%= link_to "Sign-in with Google Authentication.", new_user_session_path, class: 'button'  %>
<% end %>


<!--
Debug information
<% @events.each do |x| %>
<%= x.summary %> <strong>by</strong> <%= x.owner %><br>
<% end %>

<%= debug @list_events %>
-->

app/views/events/new.html.erb
<%= form_for (@event) do |f| %>
    <h3>Event title:</h3>
    <%= f.text_field :summary %><br>
    <h3>Event Description:</h3>
    <%= f.text_field :description %><br>
    <h3>Location:</h3>
    <%= f.text_field :location %><br>
    <h3>Attendees (Separate e-mails with a comma):</h1>
    <%= f.text_field :attendees %>
    <h3>Start Time:</h3>
    <%= f.datetime_select(:start) %><br>
    <h3>End Time:</h3>
    <%= f.datetime_select(:end) %><br>
    <%= f.submit 'Add Event' %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <%= content_tag :div, msg, :class => "flash_#{name}" %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MobiquityCalendarApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/messages' %>
<%= yield %>

</body>
</html>